# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host Starting the synchronization process
      mkdir copyrepo
      $sourceURL = "https://${env:GITHUBPAT}${env:GITHUBTESTPATH}"
      $destURL = "https://${env:DEVOPSPAT}${env:DEVOPSTESTPATH}"
      Set-Location "$(Build.SourcesDirectory)/copyrepo"
      git clone --mirror $sourceURL
      Set-Location "$(Build.SourcesDirectory)/copyrepo/Test/"
      Write-Host "*****Git removing remote origin****"
      git remote rm origin
      Write-Output "*****Git remote add****"
      git remote add --mirror=fetch origin $destURL
      Write-Output "*****Git fetch origin****"
      git fetch $sourceURL
      Write-Output "*****Git push to Azure Repos****"
      git push origin --all -f
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
